version: '3'
services:
  sinatra:
    build: ruby
    ports:
      - "${RUBY_PORT:?}:4567"
    environment:
      - PYTHON_PORT=${PYTHON_PORT:?}
  flask:
    build: python
    environment:
      - PORT=${PYTHON_PORT:?}